#############################################################################
# Makefile for building: Geom3D/TP_Geom3D/bin/proj_model
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  Geom3D/TP_Geom3D/Projet_modeling/Projet_modeling.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 CONFIG+=debug -o Makefile Geom3D/TP_Geom3D/Projet_modeling/Projet_modeling.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -DSHADERPATH=/home/finnell/Desktop/ProjetGeo3D/Geom3D/TP_Geom3D/Projet_modeling -std=c++11 -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -IGeom3D/TP_Geom3D/Projet_modeling -I. -IGeom3D/TP_Geom3D -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = proj_model1.0.0
DISTDIR = /home/finnell/Desktop/ProjetGeo3D/.tmp/proj_model1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-rpath,/home/finnell/Desktop/ProjetGeo3D/Geom3D/TP_Geom3D/Projet_modeling/../bin
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -L/home/finnell/Desktop/ProjetGeo3D/Geom3D/TP_Geom3D/Projet_modeling/../bin -lOGLRender -lQGLViewer33 -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Xml -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Geom3D/TP_Geom3D/Projet_modeling/main.cpp \
		Geom3D/TP_Geom3D/Projet_modeling/viewer.cpp \
		Geom3D/TP_Geom3D/Projet_modeling/primitives.cpp \
		Geom3D/TP_Geom3D/Projet_modeling/meshquad.cpp moc_viewer.cpp
OBJECTS       = main.o \
		viewer.o \
		primitives.o \
		meshquad.o \
		moc_viewer.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Geom3D/TP_Geom3D/Projet_modeling/Geom3D/TP_Geom3D/Projet_modeling/Projet_modeling.pro Geom3D/TP_Geom3D/Projet_modeling/viewer.h \
		Geom3D/TP_Geom3D/Projet_modeling/matrices.h \
		Geom3D/TP_Geom3D/Projet_modeling/primitives.h \
		Geom3D/TP_Geom3D/Projet_modeling/meshquad.h Geom3D/TP_Geom3D/Projet_modeling/main.cpp \
		Geom3D/TP_Geom3D/Projet_modeling/viewer.cpp \
		Geom3D/TP_Geom3D/Projet_modeling/primitives.cpp \
		Geom3D/TP_Geom3D/Projet_modeling/meshquad.cpp
QMAKE_TARGET  = proj_model
DESTDIR       = Geom3D/TP_Geom3D/bin/#avoid trailing-slash linebreak
TARGET        = Geom3D/TP_Geom3D/bin/proj_model


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d Geom3D/TP_Geom3D/bin/ || mkdir -p Geom3D/TP_Geom3D/bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Geom3D/TP_Geom3D/Projet_modeling/Projet_modeling.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Geom3D/TP_Geom3D/Projet_modeling/Projet_modeling.pro \
		/usr/lib/x86_64-linux-gnu/libQt5OpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Xml.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -spec linux-g++-64 CONFIG+=debug -o Makefile Geom3D/TP_Geom3D/Projet_modeling/Projet_modeling.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Geom3D/TP_Geom3D/Projet_modeling/Projet_modeling.pro:
/usr/lib/x86_64-linux-gnu/libQt5OpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Xml.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 CONFIG+=debug -o Makefile Geom3D/TP_Geom3D/Projet_modeling/Projet_modeling.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents Geom3D/TP_Geom3D/Projet_modeling/viewer.h Geom3D/TP_Geom3D/Projet_modeling/matrices.h Geom3D/TP_Geom3D/Projet_modeling/primitives.h Geom3D/TP_Geom3D/Projet_modeling/meshquad.h $(DISTDIR)/
	$(COPY_FILE) --parents Geom3D/TP_Geom3D/Projet_modeling/main.cpp Geom3D/TP_Geom3D/Projet_modeling/viewer.cpp Geom3D/TP_Geom3D/Projet_modeling/primitives.cpp Geom3D/TP_Geom3D/Projet_modeling/meshquad.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_viewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_viewer.cpp
moc_viewer.cpp: Geom3D/TP_Geom3D/GL/glew.h \
		Geom3D/TP_Geom3D/QGLViewer/qglviewer.h \
		Geom3D/TP_Geom3D/QGLViewer/camera.h \
		Geom3D/TP_Geom3D/QGLViewer/keyFrameInterpolator.h \
		Geom3D/TP_Geom3D/QGLViewer/quaternion.h \
		Geom3D/TP_Geom3D/QGLViewer/vec.h \
		Geom3D/TP_Geom3D/QGLViewer/config.h \
		Geom3D/TP_Geom3D/QGLViewer/frame.h \
		Geom3D/TP_Geom3D/QGLViewer/constraint.h \
		Geom3D/TP_Geom3D/OGLRender/shaderprogramcolor.h \
		Geom3D/TP_Geom3D/OGLRender/shaderprogram.h \
		Geom3D/TP_Geom3D/glm/glm.hpp \
		Geom3D/TP_Geom3D/glm/detail/_fixes.hpp \
		Geom3D/TP_Geom3D/glm/fwd.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_int.hpp \
		Geom3D/TP_Geom3D/glm/detail/setup.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_float.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec.hpp \
		Geom3D/TP_Geom3D/glm/detail/precision.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat.hpp \
		Geom3D/TP_Geom3D/glm/vec2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec2.hpp \
		Geom3D/TP_Geom3D/glm/detail/_swizzle.hpp \
		Geom3D/TP_Geom3D/glm/detail/_swizzle_func.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec2.inl \
		Geom3D/TP_Geom3D/glm/vec3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec3.inl \
		Geom3D/TP_Geom3D/glm/vec4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec4.inl \
		Geom3D/TP_Geom3D/glm/detail/type_vec4_sse2.inl \
		Geom3D/TP_Geom3D/glm/detail/type_vec4_avx.inl \
		Geom3D/TP_Geom3D/glm/detail/type_vec4_avx2.inl \
		Geom3D/TP_Geom3D/glm/mat2x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x2.inl \
		Geom3D/TP_Geom3D/glm/mat2x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x3.inl \
		Geom3D/TP_Geom3D/glm/mat2x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x4.inl \
		Geom3D/TP_Geom3D/glm/mat3x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x2.inl \
		Geom3D/TP_Geom3D/glm/mat3x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x3.inl \
		Geom3D/TP_Geom3D/glm/mat3x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x4.inl \
		Geom3D/TP_Geom3D/glm/mat4x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x2.inl \
		Geom3D/TP_Geom3D/glm/mat4x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x3.inl \
		Geom3D/TP_Geom3D/glm/mat4x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x4.inl \
		Geom3D/TP_Geom3D/glm/trigonometric.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_trigonometric.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_trigonometric.inl \
		Geom3D/TP_Geom3D/glm/detail/_vectorize.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec1.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec1.inl \
		Geom3D/TP_Geom3D/glm/exponential.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_exponential.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_exponential.inl \
		Geom3D/TP_Geom3D/glm/detail/func_vector_relational.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_vector_relational.inl \
		Geom3D/TP_Geom3D/glm/common.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_common.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_common.inl \
		Geom3D/TP_Geom3D/glm/packing.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_packing.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_packing.inl \
		Geom3D/TP_Geom3D/glm/detail/type_half.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_half.inl \
		Geom3D/TP_Geom3D/glm/geometric.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_geometric.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_geometric.inl \
		Geom3D/TP_Geom3D/glm/matrix.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_matrix.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_matrix.inl \
		Geom3D/TP_Geom3D/glm/vector_relational.hpp \
		Geom3D/TP_Geom3D/glm/integer.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_integer.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_integer.inl \
		Geom3D/TP_Geom3D/glm/gtc/type_ptr.hpp \
		Geom3D/TP_Geom3D/glm/gtc/quaternion.hpp \
		Geom3D/TP_Geom3D/glm/gtc/constants.hpp \
		Geom3D/TP_Geom3D/glm/gtc/constants.inl \
		Geom3D/TP_Geom3D/glm/gtc/quaternion.inl \
		Geom3D/TP_Geom3D/glm/gtc/type_ptr.inl \
		Geom3D/TP_Geom3D/glm/gtc/matrix_inverse.hpp \
		Geom3D/TP_Geom3D/glm/gtc/matrix_inverse.inl \
		Geom3D/TP_Geom3D/OGLRender/shader.h \
		Geom3D/TP_Geom3D/Projet_modeling/matrices.h \
		Geom3D/TP_Geom3D/glm/gtx/transform.hpp \
		Geom3D/TP_Geom3D/glm/gtc/matrix_transform.hpp \
		Geom3D/TP_Geom3D/glm/gtc/matrix_transform.inl \
		Geom3D/TP_Geom3D/glm/gtx/transform.inl \
		Geom3D/TP_Geom3D/Projet_modeling/primitives.h \
		Geom3D/TP_Geom3D/OGLRender/shaderprogramflat.h \
		Geom3D/TP_Geom3D/Projet_modeling/meshquad.h \
		Geom3D/TP_Geom3D/Projet_modeling/viewer.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/finnell/Desktop/ProjetGeo3D/Geom3D/TP_Geom3D/Projet_modeling -I/home/finnell/Desktop/ProjetGeo3D/Geom3D/TP_Geom3D -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Geom3D/TP_Geom3D/Projet_modeling/viewer.h -o moc_viewer.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: Geom3D/TP_Geom3D/Projet_modeling/main.cpp Geom3D/TP_Geom3D/Projet_modeling/viewer.h \
		Geom3D/TP_Geom3D/GL/glew.h \
		Geom3D/TP_Geom3D/QGLViewer/qglviewer.h \
		Geom3D/TP_Geom3D/QGLViewer/camera.h \
		Geom3D/TP_Geom3D/QGLViewer/keyFrameInterpolator.h \
		Geom3D/TP_Geom3D/QGLViewer/quaternion.h \
		Geom3D/TP_Geom3D/QGLViewer/vec.h \
		Geom3D/TP_Geom3D/QGLViewer/config.h \
		Geom3D/TP_Geom3D/QGLViewer/frame.h \
		Geom3D/TP_Geom3D/QGLViewer/constraint.h \
		Geom3D/TP_Geom3D/OGLRender/shaderprogramcolor.h \
		Geom3D/TP_Geom3D/OGLRender/shaderprogram.h \
		Geom3D/TP_Geom3D/glm/glm.hpp \
		Geom3D/TP_Geom3D/glm/detail/_fixes.hpp \
		Geom3D/TP_Geom3D/glm/fwd.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_int.hpp \
		Geom3D/TP_Geom3D/glm/detail/setup.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_float.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec.hpp \
		Geom3D/TP_Geom3D/glm/detail/precision.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat.hpp \
		Geom3D/TP_Geom3D/glm/vec2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec2.hpp \
		Geom3D/TP_Geom3D/glm/detail/_swizzle.hpp \
		Geom3D/TP_Geom3D/glm/detail/_swizzle_func.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec2.inl \
		Geom3D/TP_Geom3D/glm/vec3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec3.inl \
		Geom3D/TP_Geom3D/glm/vec4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec4.inl \
		Geom3D/TP_Geom3D/glm/detail/type_vec4_sse2.inl \
		Geom3D/TP_Geom3D/glm/detail/type_vec4_avx.inl \
		Geom3D/TP_Geom3D/glm/detail/type_vec4_avx2.inl \
		Geom3D/TP_Geom3D/glm/mat2x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x2.inl \
		Geom3D/TP_Geom3D/glm/mat2x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x3.inl \
		Geom3D/TP_Geom3D/glm/mat2x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x4.inl \
		Geom3D/TP_Geom3D/glm/mat3x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x2.inl \
		Geom3D/TP_Geom3D/glm/mat3x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x3.inl \
		Geom3D/TP_Geom3D/glm/mat3x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x4.inl \
		Geom3D/TP_Geom3D/glm/mat4x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x2.inl \
		Geom3D/TP_Geom3D/glm/mat4x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x3.inl \
		Geom3D/TP_Geom3D/glm/mat4x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x4.inl \
		Geom3D/TP_Geom3D/glm/trigonometric.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_trigonometric.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_trigonometric.inl \
		Geom3D/TP_Geom3D/glm/detail/_vectorize.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec1.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec1.inl \
		Geom3D/TP_Geom3D/glm/exponential.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_exponential.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_exponential.inl \
		Geom3D/TP_Geom3D/glm/detail/func_vector_relational.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_vector_relational.inl \
		Geom3D/TP_Geom3D/glm/common.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_common.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_common.inl \
		Geom3D/TP_Geom3D/glm/packing.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_packing.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_packing.inl \
		Geom3D/TP_Geom3D/glm/detail/type_half.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_half.inl \
		Geom3D/TP_Geom3D/glm/geometric.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_geometric.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_geometric.inl \
		Geom3D/TP_Geom3D/glm/matrix.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_matrix.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_matrix.inl \
		Geom3D/TP_Geom3D/glm/vector_relational.hpp \
		Geom3D/TP_Geom3D/glm/integer.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_integer.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_integer.inl \
		Geom3D/TP_Geom3D/glm/gtc/type_ptr.hpp \
		Geom3D/TP_Geom3D/glm/gtc/quaternion.hpp \
		Geom3D/TP_Geom3D/glm/gtc/constants.hpp \
		Geom3D/TP_Geom3D/glm/gtc/constants.inl \
		Geom3D/TP_Geom3D/glm/gtc/quaternion.inl \
		Geom3D/TP_Geom3D/glm/gtc/type_ptr.inl \
		Geom3D/TP_Geom3D/glm/gtc/matrix_inverse.hpp \
		Geom3D/TP_Geom3D/glm/gtc/matrix_inverse.inl \
		Geom3D/TP_Geom3D/OGLRender/shader.h \
		Geom3D/TP_Geom3D/Projet_modeling/matrices.h \
		Geom3D/TP_Geom3D/glm/gtx/transform.hpp \
		Geom3D/TP_Geom3D/glm/gtc/matrix_transform.hpp \
		Geom3D/TP_Geom3D/glm/gtc/matrix_transform.inl \
		Geom3D/TP_Geom3D/glm/gtx/transform.inl \
		Geom3D/TP_Geom3D/Projet_modeling/primitives.h \
		Geom3D/TP_Geom3D/OGLRender/shaderprogramflat.h \
		Geom3D/TP_Geom3D/Projet_modeling/meshquad.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o Geom3D/TP_Geom3D/Projet_modeling/main.cpp

viewer.o: Geom3D/TP_Geom3D/Projet_modeling/viewer.cpp Geom3D/TP_Geom3D/Projet_modeling/viewer.h \
		Geom3D/TP_Geom3D/GL/glew.h \
		Geom3D/TP_Geom3D/QGLViewer/qglviewer.h \
		Geom3D/TP_Geom3D/QGLViewer/camera.h \
		Geom3D/TP_Geom3D/QGLViewer/keyFrameInterpolator.h \
		Geom3D/TP_Geom3D/QGLViewer/quaternion.h \
		Geom3D/TP_Geom3D/QGLViewer/vec.h \
		Geom3D/TP_Geom3D/QGLViewer/config.h \
		Geom3D/TP_Geom3D/QGLViewer/frame.h \
		Geom3D/TP_Geom3D/QGLViewer/constraint.h \
		Geom3D/TP_Geom3D/OGLRender/shaderprogramcolor.h \
		Geom3D/TP_Geom3D/OGLRender/shaderprogram.h \
		Geom3D/TP_Geom3D/glm/glm.hpp \
		Geom3D/TP_Geom3D/glm/detail/_fixes.hpp \
		Geom3D/TP_Geom3D/glm/fwd.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_int.hpp \
		Geom3D/TP_Geom3D/glm/detail/setup.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_float.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec.hpp \
		Geom3D/TP_Geom3D/glm/detail/precision.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat.hpp \
		Geom3D/TP_Geom3D/glm/vec2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec2.hpp \
		Geom3D/TP_Geom3D/glm/detail/_swizzle.hpp \
		Geom3D/TP_Geom3D/glm/detail/_swizzle_func.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec2.inl \
		Geom3D/TP_Geom3D/glm/vec3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec3.inl \
		Geom3D/TP_Geom3D/glm/vec4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec4.inl \
		Geom3D/TP_Geom3D/glm/detail/type_vec4_sse2.inl \
		Geom3D/TP_Geom3D/glm/detail/type_vec4_avx.inl \
		Geom3D/TP_Geom3D/glm/detail/type_vec4_avx2.inl \
		Geom3D/TP_Geom3D/glm/mat2x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x2.inl \
		Geom3D/TP_Geom3D/glm/mat2x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x3.inl \
		Geom3D/TP_Geom3D/glm/mat2x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x4.inl \
		Geom3D/TP_Geom3D/glm/mat3x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x2.inl \
		Geom3D/TP_Geom3D/glm/mat3x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x3.inl \
		Geom3D/TP_Geom3D/glm/mat3x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x4.inl \
		Geom3D/TP_Geom3D/glm/mat4x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x2.inl \
		Geom3D/TP_Geom3D/glm/mat4x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x3.inl \
		Geom3D/TP_Geom3D/glm/mat4x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x4.inl \
		Geom3D/TP_Geom3D/glm/trigonometric.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_trigonometric.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_trigonometric.inl \
		Geom3D/TP_Geom3D/glm/detail/_vectorize.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec1.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec1.inl \
		Geom3D/TP_Geom3D/glm/exponential.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_exponential.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_exponential.inl \
		Geom3D/TP_Geom3D/glm/detail/func_vector_relational.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_vector_relational.inl \
		Geom3D/TP_Geom3D/glm/common.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_common.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_common.inl \
		Geom3D/TP_Geom3D/glm/packing.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_packing.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_packing.inl \
		Geom3D/TP_Geom3D/glm/detail/type_half.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_half.inl \
		Geom3D/TP_Geom3D/glm/geometric.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_geometric.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_geometric.inl \
		Geom3D/TP_Geom3D/glm/matrix.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_matrix.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_matrix.inl \
		Geom3D/TP_Geom3D/glm/vector_relational.hpp \
		Geom3D/TP_Geom3D/glm/integer.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_integer.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_integer.inl \
		Geom3D/TP_Geom3D/glm/gtc/type_ptr.hpp \
		Geom3D/TP_Geom3D/glm/gtc/quaternion.hpp \
		Geom3D/TP_Geom3D/glm/gtc/constants.hpp \
		Geom3D/TP_Geom3D/glm/gtc/constants.inl \
		Geom3D/TP_Geom3D/glm/gtc/quaternion.inl \
		Geom3D/TP_Geom3D/glm/gtc/type_ptr.inl \
		Geom3D/TP_Geom3D/glm/gtc/matrix_inverse.hpp \
		Geom3D/TP_Geom3D/glm/gtc/matrix_inverse.inl \
		Geom3D/TP_Geom3D/OGLRender/shader.h \
		Geom3D/TP_Geom3D/Projet_modeling/matrices.h \
		Geom3D/TP_Geom3D/glm/gtx/transform.hpp \
		Geom3D/TP_Geom3D/glm/gtc/matrix_transform.hpp \
		Geom3D/TP_Geom3D/glm/gtc/matrix_transform.inl \
		Geom3D/TP_Geom3D/glm/gtx/transform.inl \
		Geom3D/TP_Geom3D/Projet_modeling/primitives.h \
		Geom3D/TP_Geom3D/OGLRender/shaderprogramflat.h \
		Geom3D/TP_Geom3D/Projet_modeling/meshquad.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewer.o Geom3D/TP_Geom3D/Projet_modeling/viewer.cpp

primitives.o: Geom3D/TP_Geom3D/Projet_modeling/primitives.cpp Geom3D/TP_Geom3D/Projet_modeling/primitives.h \
		Geom3D/TP_Geom3D/OGLRender/shaderprogramflat.h \
		Geom3D/TP_Geom3D/OGLRender/shaderprogram.h \
		Geom3D/TP_Geom3D/GL/glew.h \
		Geom3D/TP_Geom3D/glm/glm.hpp \
		Geom3D/TP_Geom3D/glm/detail/_fixes.hpp \
		Geom3D/TP_Geom3D/glm/fwd.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_int.hpp \
		Geom3D/TP_Geom3D/glm/detail/setup.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_float.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec.hpp \
		Geom3D/TP_Geom3D/glm/detail/precision.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat.hpp \
		Geom3D/TP_Geom3D/glm/vec2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec2.hpp \
		Geom3D/TP_Geom3D/glm/detail/_swizzle.hpp \
		Geom3D/TP_Geom3D/glm/detail/_swizzle_func.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec2.inl \
		Geom3D/TP_Geom3D/glm/vec3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec3.inl \
		Geom3D/TP_Geom3D/glm/vec4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec4.inl \
		Geom3D/TP_Geom3D/glm/detail/type_vec4_sse2.inl \
		Geom3D/TP_Geom3D/glm/detail/type_vec4_avx.inl \
		Geom3D/TP_Geom3D/glm/detail/type_vec4_avx2.inl \
		Geom3D/TP_Geom3D/glm/mat2x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x2.inl \
		Geom3D/TP_Geom3D/glm/mat2x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x3.inl \
		Geom3D/TP_Geom3D/glm/mat2x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x4.inl \
		Geom3D/TP_Geom3D/glm/mat3x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x2.inl \
		Geom3D/TP_Geom3D/glm/mat3x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x3.inl \
		Geom3D/TP_Geom3D/glm/mat3x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x4.inl \
		Geom3D/TP_Geom3D/glm/mat4x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x2.inl \
		Geom3D/TP_Geom3D/glm/mat4x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x3.inl \
		Geom3D/TP_Geom3D/glm/mat4x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x4.inl \
		Geom3D/TP_Geom3D/glm/trigonometric.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_trigonometric.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_trigonometric.inl \
		Geom3D/TP_Geom3D/glm/detail/_vectorize.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec1.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec1.inl \
		Geom3D/TP_Geom3D/glm/exponential.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_exponential.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_exponential.inl \
		Geom3D/TP_Geom3D/glm/detail/func_vector_relational.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_vector_relational.inl \
		Geom3D/TP_Geom3D/glm/common.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_common.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_common.inl \
		Geom3D/TP_Geom3D/glm/packing.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_packing.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_packing.inl \
		Geom3D/TP_Geom3D/glm/detail/type_half.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_half.inl \
		Geom3D/TP_Geom3D/glm/geometric.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_geometric.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_geometric.inl \
		Geom3D/TP_Geom3D/glm/matrix.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_matrix.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_matrix.inl \
		Geom3D/TP_Geom3D/glm/vector_relational.hpp \
		Geom3D/TP_Geom3D/glm/integer.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_integer.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_integer.inl \
		Geom3D/TP_Geom3D/glm/gtc/type_ptr.hpp \
		Geom3D/TP_Geom3D/glm/gtc/quaternion.hpp \
		Geom3D/TP_Geom3D/glm/gtc/constants.hpp \
		Geom3D/TP_Geom3D/glm/gtc/constants.inl \
		Geom3D/TP_Geom3D/glm/gtc/quaternion.inl \
		Geom3D/TP_Geom3D/glm/gtc/type_ptr.inl \
		Geom3D/TP_Geom3D/glm/gtc/matrix_inverse.hpp \
		Geom3D/TP_Geom3D/glm/gtc/matrix_inverse.inl \
		Geom3D/TP_Geom3D/OGLRender/shader.h \
		Geom3D/TP_Geom3D/Projet_modeling/matrices.h \
		Geom3D/TP_Geom3D/glm/gtx/transform.hpp \
		Geom3D/TP_Geom3D/glm/gtc/matrix_transform.hpp \
		Geom3D/TP_Geom3D/glm/gtc/matrix_transform.inl \
		Geom3D/TP_Geom3D/glm/gtx/transform.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o primitives.o Geom3D/TP_Geom3D/Projet_modeling/primitives.cpp

meshquad.o: Geom3D/TP_Geom3D/Projet_modeling/meshquad.cpp Geom3D/TP_Geom3D/Projet_modeling/meshquad.h \
		Geom3D/TP_Geom3D/OGLRender/shaderprogramflat.h \
		Geom3D/TP_Geom3D/OGLRender/shaderprogram.h \
		Geom3D/TP_Geom3D/GL/glew.h \
		Geom3D/TP_Geom3D/glm/glm.hpp \
		Geom3D/TP_Geom3D/glm/detail/_fixes.hpp \
		Geom3D/TP_Geom3D/glm/fwd.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_int.hpp \
		Geom3D/TP_Geom3D/glm/detail/setup.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_float.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec.hpp \
		Geom3D/TP_Geom3D/glm/detail/precision.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat.hpp \
		Geom3D/TP_Geom3D/glm/vec2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec2.hpp \
		Geom3D/TP_Geom3D/glm/detail/_swizzle.hpp \
		Geom3D/TP_Geom3D/glm/detail/_swizzle_func.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec2.inl \
		Geom3D/TP_Geom3D/glm/vec3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec3.inl \
		Geom3D/TP_Geom3D/glm/vec4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec4.inl \
		Geom3D/TP_Geom3D/glm/detail/type_vec4_sse2.inl \
		Geom3D/TP_Geom3D/glm/detail/type_vec4_avx.inl \
		Geom3D/TP_Geom3D/glm/detail/type_vec4_avx2.inl \
		Geom3D/TP_Geom3D/glm/mat2x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x2.inl \
		Geom3D/TP_Geom3D/glm/mat2x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x3.inl \
		Geom3D/TP_Geom3D/glm/mat2x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat2x4.inl \
		Geom3D/TP_Geom3D/glm/mat3x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x2.inl \
		Geom3D/TP_Geom3D/glm/mat3x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x3.inl \
		Geom3D/TP_Geom3D/glm/mat3x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat3x4.inl \
		Geom3D/TP_Geom3D/glm/mat4x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x2.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x2.inl \
		Geom3D/TP_Geom3D/glm/mat4x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x3.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x3.inl \
		Geom3D/TP_Geom3D/glm/mat4x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x4.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_mat4x4.inl \
		Geom3D/TP_Geom3D/glm/trigonometric.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_trigonometric.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_trigonometric.inl \
		Geom3D/TP_Geom3D/glm/detail/_vectorize.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec1.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_vec1.inl \
		Geom3D/TP_Geom3D/glm/exponential.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_exponential.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_exponential.inl \
		Geom3D/TP_Geom3D/glm/detail/func_vector_relational.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_vector_relational.inl \
		Geom3D/TP_Geom3D/glm/common.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_common.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_common.inl \
		Geom3D/TP_Geom3D/glm/packing.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_packing.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_packing.inl \
		Geom3D/TP_Geom3D/glm/detail/type_half.hpp \
		Geom3D/TP_Geom3D/glm/detail/type_half.inl \
		Geom3D/TP_Geom3D/glm/geometric.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_geometric.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_geometric.inl \
		Geom3D/TP_Geom3D/glm/matrix.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_matrix.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_matrix.inl \
		Geom3D/TP_Geom3D/glm/vector_relational.hpp \
		Geom3D/TP_Geom3D/glm/integer.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_integer.hpp \
		Geom3D/TP_Geom3D/glm/detail/func_integer.inl \
		Geom3D/TP_Geom3D/glm/gtc/type_ptr.hpp \
		Geom3D/TP_Geom3D/glm/gtc/quaternion.hpp \
		Geom3D/TP_Geom3D/glm/gtc/constants.hpp \
		Geom3D/TP_Geom3D/glm/gtc/constants.inl \
		Geom3D/TP_Geom3D/glm/gtc/quaternion.inl \
		Geom3D/TP_Geom3D/glm/gtc/type_ptr.inl \
		Geom3D/TP_Geom3D/glm/gtc/matrix_inverse.hpp \
		Geom3D/TP_Geom3D/glm/gtc/matrix_inverse.inl \
		Geom3D/TP_Geom3D/OGLRender/shader.h \
		Geom3D/TP_Geom3D/OGLRender/shaderprogramcolor.h \
		Geom3D/TP_Geom3D/Projet_modeling/matrices.h \
		Geom3D/TP_Geom3D/glm/gtx/transform.hpp \
		Geom3D/TP_Geom3D/glm/gtc/matrix_transform.hpp \
		Geom3D/TP_Geom3D/glm/gtc/matrix_transform.inl \
		Geom3D/TP_Geom3D/glm/gtx/transform.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o meshquad.o Geom3D/TP_Geom3D/Projet_modeling/meshquad.cpp

moc_viewer.o: moc_viewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewer.o moc_viewer.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

